#!/bin/bash

mkdir -p dist

NODE_ENV=production node_modules/.bin/browserify lib/index.js \
  -t reactify \
  -t browserify-shim \
  -t envify \
  --detect-globals false \
  -s ReactImageLightbox > dist/react-image-lightbox.js

node_modules/.bin/uglifyjs dist/react-image-lightbox.js \
  --comments --compress warnings=false > dist/react-image-lightbox.min.js
